version: '3.5'

services:
  apigateway.presentation.web:
    image: ${REGISTRY:-zeta}/apigateway.presentation.web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: services/ApiGateway/src/ApiGateway.Presentation.Web/Dockerfile

  customers.presentation.web:
    image: ${REGISTRY:-zeta}/customers.presentation.web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: services/Customers/src/Customers.Presentation.Web/Dockerfile

  orders.presentation.web:
    image: ${REGISTRY:-zeta}/orders.presentation.web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: services/Orders/src/Orders.Presentation.Web/Dockerfile