@auth_baseurl = http://localhost:8080
@auth_realm = master
@auth_username = admin
@auth_password = admin
@client_id = zeta
@client_secret = zeta

###################################################################################
#### AUTH get openid configuration
GET {{auth_baseurl}}/auth/realms/{{auth_realm}}/.well-known/openid-configuration HTTP/1.1
Content-Type: application/json

###################################################################################
### AUTH sign in (password)
# @name sign_in_password
@access_token = {{sign_in_password.response.body.$.access_token}}
@refresh_token = {{sign_in_password.response.body.$.refresh_token}}

POST {{auth_baseurl}}/auth/realms/{{auth_realm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}
&username={{auth_username}}
&password={{auth_password}}

###################################################################################
### AUTH sign in (client_credentials)
# @name sign_in_client_credentials
@access_token = {{sign_in_client_credentials.response.body.$.access_token}}
@refresh_token = {{sign_in_client_credentials.response.body.$.refresh_token}}

POST {{auth_baseurl}}/auth/realms/{{auth_realm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}

###################################################################################
### AUTH get user info
GET {{auth_baseurl}}/auth/realms/{{auth_realm}}/protocol/openid-connect/userinfo HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###################################################################################
### AUTH get account info
GET {{auth_baseurl}}/auth/realms/{{auth_realm}}/account HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###################################################################################
### AUTH refresh tokens https://identitymodel.readthedocs.io/en/latest/client/token.html#requesting-a-token-using-the-refresh-token-grant-type
# @name refresh_token_request
# @access_token = {{refresh_token_request.response.body.$.access_token}}
# @refresh_token = {{refresh_token_request.response.body.$.refresh_token}}

POST {{auth_baseurl}}/auth/realms/{{auth_realm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{client_id}}
&client_secret={{client_secret}}
&refresh_token={{refresh_token}}

###################################################################################
### API get Api Gateway health                                                    #
GET https://localhost:6100/health HTTP/1.1
Content-Type: application/json

### API get Api Gateway echo                                                      #
GET https://localhost:6100/api/v1/_echo HTTP/1.1
Content-Type: application/json

### API get Api Gateway systeminformation                                                      #
GET https://localhost:6100/api/v1/_systeminformation HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###################################################################################
### API get Customers Service health (Gateway)                                             #
GET https://localhost:6100/customers/health HTTP/1.1
Content-Type: application/json

### API get Customers Service echo (Gateway)                                              #
GET https://localhost:6100/customers/api/v1/_echo HTTP/1.1
Content-Type: application/json

### API get Customers Service echo (Direct)                                       #
GET http://localhost:6001/api/v1/_echo HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

### API get Customers Service systeminformation (Direct)                                                      #
GET http://localhost:6001/api/v1/_systeminformation HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

###################################################################################
### API get Orders Service health (Gateway)h                                                 #
GET https://localhost:6100/orders/health HTTP/1.1
Content-Type: application/json

### API get Orders Service echo (Gateway)                                                 #
GET https://localhost:6100/orders/api/v1/_echo HTTP/1.1
Content-Type: application/json

### API get Orders Service echo (Direct)                                          #
GET http://localhost:6002/api/v1/_echo HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

### API get Orders Service systeminformation (Direct)                                                      #
GET http://localhost:6002/api/v1/_systeminformation HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json