version: "3.5"

services:
#  portainer:
#    image: portainer/portainer
#    container_name: portainer
#    restart: always
#    ports:
#      - 9000:9000 # http://localhost:9000
#    networks:
#      - zeta
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer:/data portainer/portainer
#
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      - zeta
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - zeta
    ports:
      - 9998:9998
      - 9999:9999

  sql:
    image: microsoft/mssql-server-linux
    container_name: sqlserver
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd1234!
    networks:
      - zeta
    ports:
      - 1433:1433
    volumes:
      - sqlserver:/var/opt/mssql

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - zeta
    # volumes:
    #   - grafana:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686 # http://localhost:16686/search
    networks:
      - zeta

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - zeta
    volumes:
      - mongo:/data/db

#  prometheus:
#    build: ./prometheus
#    container_name: prometheus
#    restart: unless-stopped
#    ports:
#      - 9090:9090 # http://localhost:9090/graph
#    networks:
#      - zeta
#    # volumes:
#    #   - prometheus:/prometheus

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672 # http://localhost:15672
    networks:
      - zeta
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - zeta
    volumes:
      - redis:/data

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80 # http://localhost:5341
    networks:
      - zeta
    # volumes:
    #   - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    ports:
      - 8200:8200 # http://localhost:8200
    networks:
      - zeta
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

networks:
  zeta:
    name: zeta-network

volumes:
  # portainer:
  #   driver: local
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  sqlserver:
    driver: local
  mongo:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local
