version: "3.5"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - zeta
    # volumes:
    #   - grafana:/var/lib/grafana

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - zeta
    # volumes:
    #   - prometheus:/prometheus

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - zeta

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - zeta
    # volumes:
    #   - seq:/data

networks:
  zeta:
    name: zeta-network
    external: true

# volumes:
#   grafana:
#     driver: local
#   prometheus:
#     driver: local
#   seq:
#     driver: local